name: Hausaufgabe JavaScript Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Tests ausführen
        run: npm test